# Colors & Terminal Customizations
set -g default-terminal "xterm-256color"
set-option -as terminal-overrides ",xterm*:Tc"
set-option -as terminal-overrides ",xterm*:RGB"
set-option -as terminal-overrides ",ghostty*:Tc"
set-option -as terminal-overrides ",ghostty*:RGB"
set-option -as terminal-features ",xterm*:RGB"
set-option -as terminal-features ",ghostty*:RGB"
set-option -g focus-events on
set-environment -g COLORTERM truecolor

# Keybindings & General Settings
unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded!"

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Vim-like splits
unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vim-like pane navigation & resizing
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Vim mode copy settings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Auto-install TPM if not present
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'wfxr/tmux-fzf-url'

# Session Managers
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Sessionx Settings
set -g @sessionx-bind 'o'
set -g @sessionx-x-path '~/dotfiles'
set -g @sessionx-window-mode 'on'
set -g @sessionx-preview-ratio '55%'

# Resurrect & Continuum Settings
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'ssh nvim'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'

# Catppuccin Theme Configuration (v2.x)
set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

# Status Bar Configuration
set -g status-position bottom
set -g status-left ""
set -g status-right-length 100
set -g status-left-length 100

set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_session}"

run '~/.tmux/plugins/tpm/tpm'
